function checkerboardGenStimImages(display,params)

% Get letter files loaded or generated if they don't exist
if ~exist(fullfile(params.wordEccDir,'trunk','letters.mat'),'file')
    letters = wordGenLetterVar;
    save(fullfile(params.wordEccDir,'trunk','letters.mat'),'letters');
else
    load(fullfile(params.wordEccDir,'trunk','letters.mat'));
    letters = data.letters;
end

% Set xHeights for letters (this may change to being loaded from elsewhere)
xHeights = {...
    '1degUp'        .30; ...
    '1degDown'      .30; ...
    '3degUp'        .50; ...
    '3degDown'      .50; ... 
    '6degUp'        .80; ...
    '6degDown'      .80; ...
    '1degRight'        .30; ...
    '1degLeft'      .30; ...
    '3degRight'        .50; ...
    '3degLeft'      .50; ... 
    '6degRight'        .80; ...
    '6degLeft'      .80; ...
    };

for run = 1:params.numRuns
    listTMP = eval(sprintf('params.run%02.0f;',run)); % Set words in run into tmp var
    for wordIndex = 1:length(listTMP)
        [i j] = find(strcmpi(params.conditionName{wordIndex},xHeights));
        xHeightTMP = xHeights{i,2};
        img = wordGenerateImage(display,letters,listTMP{wordIndex}, ...
            'xHeight', xHeightTMP);
        img = wordEccentricityAdjustContrast(img,242,128);
        if ~exist(fullfile(params.wordEccDir,'stim',xHeights{i,j}),'dir')
            mkdir(fullfile(params.wordEccDir,'stim',xHeights{i,j}));
        end
        imwrite(img,fullfile(params.wordEccDir,'stim',xHeights{i,j},[listTMP{wordIndex} '.bmp']));
    end
end      
