function locParamsCheck(params)
% locParamsCheck - sanity checks of parameters
%
% SOD 10/2005: wrote it.

% some checks
if params.startScan > 0,
    if round(params.startScan/params.framePeriod) ~= params.startScan/params.framePeriod
        error('start scan period (%.1f) is not an integer multiple of frame period (%.1f)!',...
            params.startScan,params.framePeriod);
    end 
end;
if round(params.prescanDuration/params.framePeriod) ~= params.prescanDuration/params.framePeriod
	error('Pre scan period (%.1f) is not an integer multiple of frame period (%.1f)!',...
        params.prescanDuration,params.framePeriod);
end
if round(params.period/params.framePeriod) ~= params.period/params.framePeriod
	error('Scan period (%.1f) is not an integer multiple of frame period (%.1f)!',...
        params.period,params.frameperiod);
end

% priority check
if params.runPriority==0
	bn = questdlg('Warning: runPriority is 0!','warning','OK','Make it 7','Make it 1','OK');
	if strmatch(bn,'Make it 7')
		params.runPriority = 7;
	elseif strmatch(bn, 'Make it 1')
		params.runPriority = 1;
	end
end

% HACK to get correct timing for 2 rings experiment, since this one is all
% hard coded.
switch params.experiment
    case '2 rings'
        params.numCycles = 1;
end;

% verification
message = sprintf(['[%s]:Scan time and MR time frames:\n' ...
                   'Duration without stimulus (junk frames 1): %5.1f sec [%3d MRtf]\n' ...
                   'Duration of prescan (junk frames 2):       %5.1f sec [%3d MRtf]\n' ...
                   'Duration of data to be collected:          %5.1f sec [%3d MRtf]\n' ...
                   'Total stimulus duration:                   %5.1f sec [%3d MRtf]\n' ...
                   'Total scan duration:                       %5.1f sec [%3d MRtf] (%.1f minutes).'], ...
               mfilename,...
               params.startScan,  params.startScan/params.framePeriod, ...
               params.prescanDuration,  params.prescanDuration/params.framePeriod,...
               params.duration.scan,  params.duration.scan/params.framePeriod,...
               params.prescanDuration + params.duration.scan,...
               params.prescanDuration/params.framePeriod + params.duration.scan/params.framePeriod,...
               params.startScan+params.prescanDuration+params.duration.scan,...
               (params.startScan+params.prescanDuration+params.duration.scan)/params.framePeriod,...
               (params.startScan+params.prescanDuration+params.duration.scan)/60);
disp(message);
